language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

compiler: gcc

install:
  - sudo apt install build-essential python python-pexpect libreadline-dev flex valgrind

script: 
  - make all && make check